// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-release.fsx"
#load "../Prelude.fs"
      "../Extensions.fs"
      "../XLinq.fs"
      "../Environment.fs"
      "../Constants.fs"
      "../Text.fs"
      "../Utilities.fs"
      "../MSBuildInfo.fs"
      "../ProjectFileInfo.fs"
      "../SolutionSystem.fs"
      "../BufferTracker.fs"
      "../FileSystem.fs"
      "../ProjectConfig.fs"
      "../HostServices.fs"
      "../Workspace.fs"
      "../MSBuildProjectSystem.fs"
