// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-release.fsx"
#load "../Prelude.fs"
      "../Extensiosn.fs"
      "../Environment.fs"
      "../Constants.fs"
      "../Utilities.fs"
      "../MSBuild.fs"
      "../ProjectInfo.fs"
      "../SolutionSystem.fs"
      "../BufferTracker.fs"
      "../FileSystem.fs"
      "../ProjectConfig.fs"
      "../Workspace.fs"
