// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-release.fsx"
#load "../Prelude.fs"
      "../Extensions.fs"
      "../Constants.fs"
      "../Environment.fs"
      "../Converters.fs"
      "../Loaders.fs"
      "../Text.fs"
      "../Commands.fs"
      "../ProjectFileInfo.fs"
      "../SolutionFileInfo.fs"
      "../BufferTracker.fs"
      "../ProjectConfig.fs"
      "../HostServices.fs"
      "../Workspace.fs"
      "../LanguageService.fs"
      "../MSBuildConfig.fs"
      "../MSBuildProjectSystem.fs"
      "../WorkspaceServices.fs"
      "../Services/ServiceInterfaces.fs"
      "../Services/Highlighting.fs"
      "../Services/QuickInfo.fs"
      "../Services/BraceMatching.fs"
